#!/bin/bash
set -e -x

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/..
BASE=$(pwd)
export GOPATH=${BASE}/build

mkdir -p ./dist/artifacts
tar -czf ./dist/artifacts/docker-machine${SUFFIX}.tar.gz -C ${GOPATH}/bin/ .
