#!/bin/bash

set -e

cd $(dirname $0)/..
BASEDIR=$(pwd)
mkdir -p $BASEDIR/build

function download_binary_unzip() {
    DRIVER_BINARY_NAME=$1
    DRIVER_SHA256=$2
    DRIVER_DOWNLOAD_URL=$3

    if [[ $(curl -sSL $DRIVER_DOWNLOAD_URL | tee $DRIVER_BINARY_NAME | openssl sha256 | sed 's/^.* //') != $DRIVER_SHA256 ]]; then
        echo 'sha256 checksum is wrong for '$DRIVER_BINARY_NAME
        exit 1
    fi

    if [ ${DRIVER_BINARY_NAME: -4} == ".zip" ]; then
        unzip -o $DRIVER_BINARY_NAME -d $BASEDIR/build/
    else
        # If the file isn't zippped
        cp $DRIVER_BINARY_NAME $BASEDIR/build/
        chmod 0755 $BASEDIR/build/$DRIVER_BINARY_NAME
    fi


    rm -rf $DRIVER_BINARY_NAME
}

function build_machine_binary() {
    mkdir -p $BASEDIR/build
    cd $BASEDIR/build

    MACHINE_REPOSITORY_URL=$1
    MACHINE_COMMIT_ID=$2

    rm -rf machine

    git clone $MACHINE_REPOSITORY_URL

    cd machine
    git checkout $MACHINE_COMMIT_ID
    TARGET_OS=linux TARGET_ARCH="amd64" ./script/build_in_container.sh build
    cp ./bin/docker-machine $BASEDIR/build/
    cd ..
    rm -rf machine
    cd $BASEDIR
}

build_machine_binary 'https://github.com/docker/machine' 'v0.14.0'

download_binary_unzip 'packet-driver.zip' 'af1a69d9c18663b6aac0c86496319651d1bfd5c8dda78fba8835e4c023622fe8' 'https://github.com/packethost/docker-machine-driver-packet/releases/download/v0.1.5/docker-machine-driver-packet_linux-amd64.zip'

mkdir -p $BASEDIR/dist/artifacts

cd $BASEDIR/build
tar -cvzf $BASEDIR/dist/artifacts/docker-machine.tar.gz *
cp docker-machine* ../bin
